// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '// Read more': https://github.com/vuejs/vue-next/pull/3399
    MainLayout: typeof import('./home/ahmedmoh/Desktop/projects/tagh-fleet/resources/ts/layouts/MainLayout.vue')['default']
  }
}

export { }
